version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: superstore_db
    restart: always
    environment:
      MYSQL_DATABASE: superstore_db
      MYSQL_USER: superstore
      MYSQL_PASSWORD: superpass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: superstore_web
    command: >
      sh -c "
      until nc -z db 3306;
      do
        echo 'Esperando a MySQL...';
        sleep 2;
      done;
      python manage.py runserver 0.0.0.0:8000
      "
    env_file:
      - .env.docker
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mysql_data: